### ISSUE TITLE
VDI: cannot create image '*.vdi' + modprobe: FATAL: Module lustre not found

### ISSUE THREAD

**Issue by aleqsio** [dctrud/dev-cluster#1]
FYI, this cluster still seems to be working, but two errors occur that are both fixable by reloading the machine and running vagrant provision.

For master it's `VDI: cannot create image '*.vdi' (VERR_ALREADY_EXISTS)`
For compute boxes it's `modprobe: FATAL: Module lustre not found`.
Both solved by running `vagrant reload NAME` and `vagrant provision NAME`

Thanks for this repo, saved me a lot of work!

**Comment by shahizat** [comment]
Hello @aleqsio, Do you know how to solve bellow issue? Thanks in advance!

Here is the error:

`    master: error: File slurm-22.05.3.tar.bz2: No such file or directory
    master: /usr/bin/cat: slurm-22.05.3.tar.bz2: No such file or directory
    master: error: File slurm-22.05.3.tar.bz2: No such file or directory
    master: /usr/bin/cat: slurm-22.05.3.tar.bz2: No such file or directory
    master: error: Failed to read spec file from slurm-22.05.3.tar.bz2
    master: Loaded plugins: fastestmirror
    master: Loading mirror speeds from cached hostfile
    master:  * base: mirror.neolabs.kz
    master:  * epel: mirror.yer.az
    master:  * extras: mirror.neolabs.kz
    master:  * updates: mirror.neolabs.kz
    master: No package /root/rpmbuild/RPMS/x86_64/slurm*.rpm available.
    master: Error: Nothing to do
    master: cp: cannot stat ‘/root/rpmbuild/RPMS/x86_64/slurm*.rpm’: No such file or directory
    master: /tmp/vagrant-shell: line 56: /etc/slurm/slurm.conf: No such file or directory
    master: Failed to execute operation: No such file or directory
    master: Failed to start slurmctld.service: Unit not found.
    master: /tmp/vagrant-shell: line 89: sinfo: command not found
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.`

**Comment by dtrudg** [comment]
Hello, this is a personal repository that I only update when needed. If you would like to fork it and make changes, please feel free.

I'll mark it archived to avoid doubt that it is maintained.
