### ISSUE TITLE
Update the scripts and vagrant file

### ISSUE THREAD

**Issue by shahizat** [dctrud/dev-cluster#2]
Hello @dtrudg, awesome project. Hope to test it soon. I'm wondering if you have an updated version of the scripts because I am experiencing a bunch of issues with the installation of Lustre and Slurm. Thanks. What do you think about to change it to Rocky Linux?

I've already changed the code snippet in the lustre_client and lustre_kernel files to:

```
# Setup repo
cat >/etc/yum.repos.d/lustre-repo.repo <<\__EOF
[lustre-server]
name=lustre-server
baseurl=https://downloads.whamcloud.com/public/lustre/lustre-2.12.8/el7.9.2009/server/
# exclude=*debuginfo*
gpgcheck=0

[lustre-client]
name=lustre-client
baseurl=https://downloads.whamcloud.com/public/lustre/lustre-2.12.8/el7.9.2009/client/
# exclude=*debuginfo*
gpgcheck=0

[e2fsprogs-wc]
name=e2fsprogs-wc
baseurl=https://downloads.whamcloud.com/public/e2fsprogs/latest/el7/
# exclude=*debuginfo*
gpgcheck=0
__EOF
```

**Comment by dtrudg** [comment]
Hello, this is a personal repository that I only update when needed. If you would like to fork it and make changes, please feel free.

I'll mark it archived to avoid doubt that it is maintained.
